sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t oneknucklehead/react-and-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true oneknucklehead/react-and-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-080875045233"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY