sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t oneknucklehead/react-and-docker -f Dockerfile.dev .

script: 
  - docker run -e CI=true oneknucklehead/react-and-docker npm run test
